### ISSUE TITLE
Several lintian errors

### ISSUE THREAD

**Issue by faveoled** [erikian/deboa#2]
I don't know if you know of lintian but it gives quite a number of errors on a sample generation:
```
N:
E: my-awesome-app: control-file-is-not-a-file ./
N: 
N:   The package contains a control file that is not a regular file.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: control-files
N: 
N:
E: my-awesome-app: description-synopsis-is-duplicated line 1
N: 
N:   The first line of the extended Description: should not repeat the synopsis
N:   exactly. This indicates that either the synopsis is badly formed or that
N:   the extended description has been wrongly copied and pasted.
N: 
N:   Please refer to Debian Policy Manual section 3.4.2 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: fields/description
N: 
N:
E: my-awesome-app: no-changelog usr/share/doc/my-awesome-app/changelog.gz (native package)
N: 
N:   A Debian package that provides a /usr/share/doc/*pkg* directory must
N:   install a changelog file.
N:   
N:   For native packages the best name is /usr/share/doc/*pkg*/changelog.gz.
N:   
N:   For non-native packages the best name is
N:   /usr/share/doc/*pkg*/changelog.Debian.gz.
N:   
N:   This tag may also be emitted when the changelog exists but does not
N:   otherwise resemble a Debian changelog.
N: 
N:   Please refer to Debian Policy Manual section 12.7 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: debian/changelog
N:   Renamed from: changelog-file-missing-in-native-package
N:   debian-changelog-file-missing
N: 
N:
E: my-awesome-app: no-copyright-file
N: 
N:   Each binary package has to include a plain file
N:   /usr/share/doc/*pkg*/copyright
N: 
N:   Please refer to Debian Policy Manual section 12.5 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: debian/copyright
N: 
N:
E: my-awesome-app: non-standard-toplevel-dir ./
N: 
N:   The Filesystem Hierarchy Standard forbids the installation of new files or
N:   directories in the root directory.
N: 
N:   Please refer to Filesystem Hierarchy Standard for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: files/hierarchy/standard
N: 
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid ./ 1000/1000
N: 
N:   The user or group ID of the owner of the file is invalid. The owner user
N:   and group IDs must be in the set of globally allocated IDs, because other
N:   IDs are dynamically allocated and might be used for varying purposes on
N:   different systems, or are reserved. The set of the allowed, globally
N:   allocated IDs consists of the ranges 0-99, 64000-64999 and 65534.
N:   
N:   It's possible for a Policy-compliant package to trigger this tag if the
N:   user is created in the preinst maintainer script, but this is a very rare
N:   case and doesn't appear to be necessary.
N: 
N:   Please refer to Debian Policy Manual section 9.2 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: files/ownership
N: 
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/usr/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/usr/bin/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/usr/bin/app.sh 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/share/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/share/applications/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/share/applications/my-awesome-app.desktop 1000/1000
N:
```
My personal use-case hits the following problems with the current generation:
* Empty "." directory within data.tar.gz, control.tar.gz
* Default uid/gid can be set to root
* /usr/lib as a destination location is not a given for all apps

**Comment by erikian** [comment]
This package is concerned with building valid .deb distributables, not so much with making lintian happy, especially because there's no easy way to run a lintian check on systems other than Linux. As long as the user provides the minimum required info, they can have a .deb in the end.

That's why deboa provides lots of ways to fine-tune the build along the way (and I'm happy to add more if necessary) and leaves details regarding metadata and package structure best practices up to the user — it can't possibly do all the checks lintian does. 

With that being said, here's the commented version of your error log:

```
### not sure about this one, could you share your .deb or at least the control file?
E: my-awesome-app: control-file-is-not-a-file ./
N: 
N:   The package contains a control file that is not a regular file.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: control-files
N: 
N:

### if you don't provide `options.controlFileOptions.extendedDescription`, it falls back to `options.controlFileOptions.shortDescription`. I should probably make the extended description a required field
E: my-awesome-app: description-synopsis-is-duplicated line 1
N: 
N:   The first line of the extended Description: should not repeat the synopsis
N:   exactly. This indicates that either the synopsis is badly formed or that
N:   the extended description has been wrongly copied and pasted.
N: 
N:   Please refer to Debian Policy Manual section 3.4.2 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: fields/description
N: 

### this seems specific to your use case
E: my-awesome-app: no-changelog usr/share/doc/my-awesome-app/changelog.gz (native package)
N: 
N:   A Debian package that provides a /usr/share/doc/*pkg* directory must
N:   install a changelog file.
N:   
N:   For native packages the best name is /usr/share/doc/*pkg*/changelog.gz.
N:   
N:   For non-native packages the best name is
N:   /usr/share/doc/*pkg*/changelog.Debian.gz.
N:   
N:   This tag may also be emitted when the changelog exists but does not
N:   otherwise resemble a Debian changelog.
N: 
N:   Please refer to Debian Policy Manual section 12.7 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: debian/changelog
N:   Renamed from: changelog-file-missing-in-native-package
N:   debian-changelog-file-missing
N: 

### while having a copyright file is required by the Debian Policy Manual, you can install and run your app just fine without one
E: my-awesome-app: no-copyright-file
N: 
N:   Each binary package has to include a plain file
N:   /usr/share/doc/*pkg*/copyright
N: 
N:   Please refer to Debian Policy Manual section 12.5 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: debian/copyright
N: 

### the tar implementation I'm using creates an empty `.` directory in the root of the .deb directory structure, but nothing gets actually copied to the `/` directory when installing the package
E: my-awesome-app: non-standard-toplevel-dir ./
N: 
N:   The Filesystem Hierarchy Standard forbids the installation of new files or
N:   directories in the root directory.
N: 
N:   Please refer to Filesystem Hierarchy Standard for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: files/hierarchy/standard
N: 

### also seems specific to your use case. if you want the files to belong to this user/group, you'd need to check for them in a `preinst` script and create them if necessary
E: my-awesome-app: wrong-file-owner-uid-or-gid ./ 1000/1000
N: 
N:   The user or group ID of the owner of the file is invalid. The owner user
N:   and group IDs must be in the set of globally allocated IDs, because other
N:   IDs are dynamically allocated and might be used for varying purposes on
N:   different systems, or are reserved. The set of the allowed, globally
N:   allocated IDs consists of the ranges 0-99, 64000-64999 and 65534.
N:   
N:   It's possible for a Policy-compliant package to trigger this tag if the
N:   user is created in the preinst maintainer script, but this is a very rare
N:   case and doesn't appear to be necessary.
N: 
N:   Please refer to Debian Policy Manual section 9.2 for details.
N: 
N:   Visibility: error
N:   Show-Always: no
N:   Check: files/ownership
N: 
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/usr/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/usr/bin/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/lib/my-awesome-app/usr/bin/app.sh 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/share/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/share/applications/ 1000/1000
N:
E: my-awesome-app: wrong-file-owner-uid-or-gid usr/share/applications/my-awesome-app.desktop 1000/1000
N:
```

About the concerns you listed:

> Empty "." directory within data.tar.gz, control.tar.gz

As noted above, it's a quirk of https://github.com/mafintosh/tar-fs IIRC. I tried changing this behavior when deboa was written, but I didn't managed to at the time.

> Default uid/gid can be set to root

Can you clarify this?

> /usr/lib as a destination location is not a given for all apps

/usr/lib is used as a sensible default, and deboa provides the `beforePackage` option which allows you to easily modify your directory structure just before packaging to serve other use cases:

```ts
import fsExtra from 'fs-extra'
import path from 'path'
import { Deboa } from 'deboa'

const deboa = new Deboa({
  beforePackage: async function (destination) {
    const newLocation = path.join(destination, '/your/desired/directory')

    await fsExtra.move(path.join(destination, 'usr', 'lib'), newLocation)
  },
  // ...other options
})
```

**Comment by faveoled** [comment]
I don't think you can say than a deb package with lintian errors is a valid deb package. 
Issues regarding changelog and copyright are not really specific to my use case. I don't provide them explicitly anywhere. I don't think it's a deal breaker, but deboa can provide some sensible defaults for these files.
```
E: my-awesome-app: control-file-is-not-a-file ./
E: my-awesome-app: non-standard-toplevel-dir ./
```
These two would be caused by a tar-fs bug.
 


> > Default uid/gid can be set to root
> 
> Can you clarify this?

AFAIK native package managers install files with their owner set to root. Otherwise we would have system files owned by a specific user, which is not good. It's nice we can override it using postinstall scripts but I'm not sure if it's the most convinient approach. Different defaults might possibly do the same job.



> /usr/lib is used as a sensible default

I'm not sure it's a sensible default at all. For me that would be "/". But deboa might just pull it as another config option

**Comment by erikian** [comment]
> AFAIK native package managers install files with their owner set to root.

By default, deboa already makes all files/folders owned by root:root (uid 0 / gid 0).

> I'm not sure it's a sensible default at all. For me that would be "/".

It _really_ depends on your use case. As per https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#shared-library-support-files:

> It is recommended that supporting files and run-time support programs that do not need to be invoked manually by users, but are nevertheless required for the package to function, be placed (if they are binary) in a subdirectory of /usr/lib, preferably under /usr/lib/package-name.

I wrote deboa as a base for https://github.com/erikian/electron-deboa-maker, so defaulting to `/usr/lib` has that use case in mind. Sure, I could add an option to specify the root directory so users could install stuff to `/some-directory` instead of `/usr/lib/some-directory`. But then what if users want to install a _file_ to the root directory (`/some-file.sh`)? Should there be an option for that too? As you can imagine, it can get complex really fast, so I think providing direct access to the directory structure is a superior option because users can change it to whatever they need and the code can be kept as simple as possible.

> I don't think you can say than a deb package with lintian errors is a valid deb package.

By "valid", I mean dpkg is able to correctly parse the package, install it and run any maintainer scripts. Lintian is just a linter, and while it's certainly useful, it doesn't necessarily mean there will be any errors when installing the app if there's a lintian error. Not the best analogy, but consider Javascript bundling/minification by Webpack and a linter like ESLint. Would the bundled .js file pass ESLint without a lot of errors? Probably not. Does that file contain valid Javascript, in the sense that it can be interpreted by Node/Chrome? Absolutely.

> Issues regarding changelog and copyright are not really specific to my use case. I don't provide them explicitly anywhere.

Could you share the directory structure you have?

**Comment by faveoled** [comment]
> By default, deboa already makes all files/folders owned by root:root (uid 0 / gid 0).

I don't think it's true. Otherwise I wouldn't have errors related to gid/uid (I use your basic JS example where no changes is made to gid/uid).
My directories are as follows:
```
my-awesome-app-linux-x64/
└── usr
    └── bin
        └── app.sh
```
*.desktop file for example is added by deboa automatically and still has id 1000

**Comment by faveoled** [comment]
> Sure, I could add an option to specify the root directory so users could install stuff to `/some-directory` instead of `/usr/lib/some-directory`. But then what if users want to install a _file_ to the root directory (`/some-file.sh`)? Should there be an option for that too?

I don't really get the complexity of it. A file within an input directory would be handled the same way as inner dirs.


> By "valid", I mean dpkg is able to correctly parse the package, install it and run any maintainer scripts.

My only objection to that would be that some GUI Linux Application Installers could have different requirements and might fail because of those deb inconsistencies. We can't know in advance if they will that's for sure

**Comment by faveoled** [comment]
> It _really_ depends on your use case. As per https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#shared-library-support-files:
I could give you this link:
https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html
/opt is used a lot for applications not included with the distribution itself. Multiple programs are installed there. That's why more flexibility could be useful

**Comment by erikian** [comment]
> I don't think it's true. Otherwise I wouldn't have errors related to gid/uid (I use your basic JS example where no changes is made to gid/uid).

You're right, the `control.tar` and `data.tar` files themselves belong to root, not their contents. I've fixed this, thank you!

> My only objection to that would be that some GUI Linux Application Installers could have different requirements and might fail because of those deb inconsistencies. We can't know in advance if they will that's for sure

That's fair, I've added the `installationRoot` option, so now you can specify where you want your app to live when it's installed (the default is still `/usr/lib/${packageName}`):

```ts
const deboa = new Deboa({
  installationRoot: '/opt',
  // ...other options
})
```

**Comment by faveoled** [comment]
I've tested `installationRoot` and it works perfectly. Still getting 1000/1000 uid/gid though. A bug might be lurking somewhere

**Comment by erikian** [comment]
Do you mind sharing a sample .deb? Also, what OS are you using?

**Comment by faveoled** [comment]
There are also lintian warnings that I haven't posted ever:
```
W: my-awesome-app: non-standard-dir-perm usr/ 0775 != 0755
N:
W: my-awesome-app: non-standard-dir-perm usr/bin/ 0775 != 0755
N:
W: my-awesome-app: non-standard-dir-perm usr/share/ 0775 != 0755
N:
W: my-awesome-app: non-standard-dir-perm usr/share/applications/ 0775 != 0755
N:
W: my-awesome-app: non-standard-file-perm usr/bin/app.sh 0664 != 0644
```
I'd like to know what is the supposed course of action here: writing custom JS code or some other setting

**Comment by erikian** [comment]
I installed your .deb on Ubuntu 22.04 and the file is owned by root as expected

![image](https://user-images.githubusercontent.com/19478575/211821540-aacb1ad0-c63b-4c24-bc72-cfd3621f26b3.png)

**Comment by faveoled** [comment]
That's good but the permissions within tar archive can still be broken

**Comment by erikian** [comment]
About the permissions, since you're on Unix, it's just copying over the permissions your files already have (I only set the permissions to `0644` / `0755` on Windows because it doesn't have chmod-style permissions).

You can either change the permissions of the files you're packaging or use the `modifyTarHeader` option to set them manually:

```js
const deboa = new Deboa({
  modifyTarHeader: header => {
    switch (header.type) {
      case 'file': {
        header.mode = parseInt('0644', 8)
        break
      }

      case 'directory': {
        header.mode = parseInt('0755', 8)
        break
      }
    }

    return header
  },
  // ...other options
})
```

**Comment by erikian** [comment]
> That's good but the permissions within tar archive can still be broken

I'll take another look, but I wouldn't be too worried about it since the file is being copied with the appropriate owner

**Comment by faveoled** [comment]
Clear, thanks

**Comment by erikian** [comment]
Fixed in https://github.com/erikian/deboa/commit/9cb03efd90b40a3d587c521fb0760704ffe13a6d. 

The `uid`/`gid` in the .tar archive were wrong as you suspected, now they're always set to `0` regardless of the current user's `uid`/`gid`. Lintian should be much happier now :smi
